Repository khaldoun-xyz/lugha, pull requests merged in 2025-02, with the labels that each got.

#52 Fix height issue in chatbot interface
  src/flask_interface/static/css/pages/chat-interface.css
Labels: bug

#54 simplify log screen concept
  docs/concept.md
  docs/files/lugha-sketch-log-accordeon.png
  docs/files/lugha-sketch-log-base.png
Labels: documentation

#55 Simplified Display of Past Conversations
  src/flask_interface/static/css/pages/main-pages.css
  src/flask_interface/templates/lugha/track_progress.html
  src/flask_interface/templates/lugha/welcome.html
Labels: enhancement

#56 Refactor/database structure
  src/evaluation_utils/create_db.py
  src/evaluation_utils/evaluate.py
  src/flask_interface/app.py
  src/utils/conversation_utils.py
  src/utils/create_db.py
  src/utils/database_utils.py
Labels: enhancement
